PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xmls: <http://www.w3.org/2001/XMLSchema#>
prefix aif: <uu:dialoguebuilder/nlpmodule/aif#>
select ?p ?q 
where { 
  ?conflict aif:conflictedElement ?p.
  ?conflict aif:conflictingElement ?q.
  ?p a aif:I-Node.
  ?q a aif:I-Node. 
}