PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xmls: <http://www.w3.org/2001/XMLSchema#>
prefix aif: <uu:dialoguebuilder/nlpmodule/aif#>
select ?label ?premiseInAntecedent ?conclusion 
where { 
  ?label aif:s-inference-node-fulfil ?scheme.
  ?scheme a aif:Presumptive-Inference-Scheme.
  ?label aif:premise ?premiseInAntecedent. 
  ?label aif:conclusion ?conclusion. 
}